const CALC_KISH = 'CALCKISH';
const CALC_KKI = 'CALCKKI';
const CALC_KZSH = 'CALC_KZSH';
const CALC_LENGTH_OF_SPURS = 'CALC_LENGTH_OF_SPURS';
const CALC_MIDDLE_DEPTH_OF_SPURS = 'CALC_MIDDLE_DEPTH_OF_SPURS';
const CALC_SPECIFIC_VV = 'CALC_SPECIFIC_VV';
const CALC_TEOR_SPEND_VV = 'CALC_TEOR_SPEND_VV';

export {
  CALC_KISH,
  CALC_KKI,
  CALC_KZSH,
  CALC_LENGTH_OF_SPURS,
  CALC_MIDDLE_DEPTH_OF_SPURS,
  CALC_SPECIFIC_VV,
  CALC_TEOR_SPEND_VV,
};
